package com.demo.taiji.models;

import java.io.Serializable;
import java.util.Date;

public class Checktable implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CheckTable.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CheckTable.date
     *
     * @mbg.generated
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CheckTable.datemonth
     *
     * @mbg.generated
     */
    private Integer datemonth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CheckTable.dateyear
     *
     * @mbg.generated
     */
    private Integer dateyear;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CheckTable.number
     *
     * @mbg.generated
     */
    private Integer number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CheckTable.program
     *
     * @mbg.generated
     */
    private String program;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CheckTable.unit
     *
     * @mbg.generated
     */
    private String unit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CheckTable.userid
     *
     * @mbg.generated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CheckTable
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CheckTable.id
     *
     * @return the value of CheckTable.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CheckTable.id
     *
     * @param id the value for CheckTable.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CheckTable.date
     *
     * @return the value of CheckTable.date
     *
     * @mbg.generated
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CheckTable.date
     *
     * @param date the value for CheckTable.date
     *
     * @mbg.generated
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CheckTable.datemonth
     *
     * @return the value of CheckTable.datemonth
     *
     * @mbg.generated
     */
    public Integer getDatemonth() {
        return datemonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CheckTable.datemonth
     *
     * @param datemonth the value for CheckTable.datemonth
     *
     * @mbg.generated
     */
    public void setDatemonth(Integer datemonth) {
        this.datemonth = datemonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CheckTable.dateyear
     *
     * @return the value of CheckTable.dateyear
     *
     * @mbg.generated
     */
    public Integer getDateyear() {
        return dateyear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CheckTable.dateyear
     *
     * @param dateyear the value for CheckTable.dateyear
     *
     * @mbg.generated
     */
    public void setDateyear(Integer dateyear) {
        this.dateyear = dateyear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CheckTable.number
     *
     * @return the value of CheckTable.number
     *
     * @mbg.generated
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CheckTable.number
     *
     * @param number the value for CheckTable.number
     *
     * @mbg.generated
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CheckTable.program
     *
     * @return the value of CheckTable.program
     *
     * @mbg.generated
     */
    public String getProgram() {
        return program;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CheckTable.program
     *
     * @param program the value for CheckTable.program
     *
     * @mbg.generated
     */
    public void setProgram(String program) {
        this.program = program == null ? null : program.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CheckTable.unit
     *
     * @return the value of CheckTable.unit
     *
     * @mbg.generated
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CheckTable.unit
     *
     * @param unit the value for CheckTable.unit
     *
     * @mbg.generated
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CheckTable.userid
     *
     * @return the value of CheckTable.userid
     *
     * @mbg.generated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CheckTable.userid
     *
     * @param userid the value for CheckTable.userid
     *
     * @mbg.generated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CheckTable
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", date=").append(date);
        sb.append(", datemonth=").append(datemonth);
        sb.append(", dateyear=").append(dateyear);
        sb.append(", number=").append(number);
        sb.append(", program=").append(program);
        sb.append(", unit=").append(unit);
        sb.append(", userid=").append(userid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}